In [ ]:
import pandas as pd

titanic_df = pd.read_csv("clean_titanic_dataset.csv")

titanic_df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,initials
0,0.0,3.0,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,0,S,Mr
1,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,1,C,Mrs
2,1.0,3.0,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,0,S,Miss
3,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,1,S,Mrs
4,0.0,3.0,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,0,S,Mr

In [3]:
from sklearn.preprocessing import OneHotEncoder

one_hot_encoder = OneHotEncoder(sparse_output=False)

In [4]:
one_hot_encoder.fit_transform(
    titanic_df[["Sex"]]
)

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [0., 1.]], shape=(874, 2))

In [5]:
one_hot_encoder.categories_

[array(['female', 'male'], dtype=object)]

In [6]:

one_hot_encoder.inverse_transform([
    [0,1],
    [1,0]
])

array([['male'],
       ['female']], dtype=object)

In [7]:
### Ordinal Data  -> data natural order
titanic_df.Embarked.value_counts()

Embarked
S    634
C    165
Q     75
Name: count, dtype: int64

In [8]:
titanic_df["encoded_embarked"] , rule = pd.factorize(titanic_df.Embarked)

In [9]:
titanic_df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,initials,encoded_embarked
0,0.0,3.0,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,0,S,Mr,0
1,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,1,C,Mrs,1
2,1.0,3.0,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,0,S,Miss,0
3,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,1,S,Mrs,0
4,0.0,3.0,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,0,S,Mr,0

In [10]:
titanic_df.encoded_embarked.value_counts()

encoded_embarked
0    634
1    165
2     75
Name: count, dtype: int64

In [11]:
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder

In [12]:
ordinal_encoder = OrdinalEncoder(dtype=int)

In [13]:
encoded_result = ordinal_encoder.fit_transform(titanic_df[["Embarked"]])

In [14]:
# encoded_result

In [15]:
ordinal_encoder.categories_

[array(['C', 'Q', 'S'], dtype=object)]

In [16]:
ordinal_encoder.inverse_transform(
    [[1],[2],[0],[1]]
)

array([['Q'],
       ['S'],
       ['C'],
       ['Q']], dtype=object)

In [17]:
final_df = titanic_df.drop(
    ["Name", "Ticket", "initials", "encoded_embarked"], axis=1
)

In [18]:
onehot_encoder = OneHotEncoder(sparse_output=False)
ordinal_encoder = OrdinalEncoder(dtype = int)

In [19]:
age_embarked_encoded = onehot_encoder.fit_transform(titanic_df[["Sex", "Embarked"]])
pclass_encoded = ordinal_encoder.fit_transform(final_df[["Pclass"]])

In [20]:
final_df.Pclass = pclass_encoded

In [21]:
final_df = pd.get_dummies(final_df, columns=["Sex", "Embarked"], dtype=int)

In [22]:
final_df.head()

,Survived,Pclass,Age,SibSp,Parch,Fare,Cabin,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,0.0,2,22.0,1.0,0.0,7.2500,0,0,1,0,0,1
1,1.0,0,38.0,1.0,0.0,71.2833,1,1,0,1,0,0
2,1.0,2,26.0,0.0,0.0,7.9250,0,1,0,0,0,1
3,1.0,0,35.0,1.0,0.0,53.1000,1,1,0,0,0,1
4,0.0,2,35.0,0.0,0.0,8.0500,0,0,1,0,0,1

In [ ]:
final_df.to_csv("encoded_titanic_dataset.csv", index = False)