Assignment: Introduction to Pandas

In [365]:
import pandas as pd

pd.__version__

'3.0.5'

In [366]:
pd.Series([10,20,30,40,50])

0    10
1    20
2    30
3    40
4    50
dtype: int64

Creating DataFrame

In [367]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [20, 22, 21, 23, 19],
    "Marks": [85, 78, 92, 88, 95],
    "City": ["Kathmandu", "Pokhara", "Lalitpur", "Bhaktapur", "Kathmandu"]
}

df = pd.DataFrame(data)
df[:3]

      Name  Age  Marks       City
0    Alice   20     85  Kathmandu
1      Bob   22     78    Pokhara
2  Charlie   21     92   Lalitpur

In [368]:
df[-2:]

    Name  Age  Marks       City
3  David   23     88  Bhaktapur
4    Eva   19     95  Kathmandu

In [369]:
# df.keys()
df.columns

Index(['Name', 'Age', 'Marks', 'City'], dtype='str')

Indexing and Selecting Data

In [370]:
df[["Name"]]

      Name
0    Alice
1      Bob
2  Charlie
3    David
4      Eva

In [371]:
df[["Name", "Marks"]]

      Name  Marks
0    Alice     85
1      Bob     78
2  Charlie     92
3    David     88
4      Eva     95

In [372]:
df.iloc[2]

Name      Charlie
Age            21
Marks          92
City     Lalitpur
Name: 2, dtype: object

In [373]:
df.loc[2]

Name      Charlie
Age            21
Marks          92
City     Lalitpur
Name: 2, dtype: object

In [374]:
df[df["Marks"] > 85]

      Name  Age  Marks       City
2  Charlie   21     92   Lalitpur
3    David   23     88  Bhaktapur
4      Eva   19     95  Kathmandu

Properties and Methods of DataFrame

In [375]:
df.shape

(5, 4)

In [376]:
df.dtypes

Name       str
Age      int64
Marks    int64
City       str
dtype: object

In [377]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
 3   City    5 non-null      str
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [378]:
df.describe()

             Age      Marks
count   5.000000   5.000000
mean   21.000000  87.600000
std     1.581139   6.580274
min    19.000000  78.000000
25%    20.000000  85.000000
50%    21.000000  88.000000
75%    22.000000  92.000000
max    23.000000  95.000000

In [379]:
df["Marks"].mean()

np.float64(87.6)

Adding and Modifying Data

In [380]:
df["Passed"] = df["Marks"] > 80
df

      Name  Age  Marks       City  Passed
0    Alice   20     85  Kathmandu    True
1      Bob   22     78    Pokhara   False
2  Charlie   21     92   Lalitpur    True
3    David   23     88  Bhaktapur    True
4      Eva   19     95  Kathmandu    True

In [381]:
df["Marks"] += 5
df

      Name  Age  Marks       City  Passed
0    Alice   20     90  Kathmandu    True
1      Bob   22     83    Pokhara   False
2  Charlie   21     97   Lalitpur    True
3    David   23     93  Bhaktapur    True
4      Eva   19    100  Kathmandu    True

In [382]:
df.loc[0, "City"] = "Chitwan"

df

      Name  Age  Marks       City  Passed
0    Alice   20     90    Chitwan    True
1      Bob   22     83    Pokhara   False
2  Charlie   21     97   Lalitpur    True
3    David   23     93  Bhaktapur    True
4      Eva   19    100  Kathmandu    True

In [383]:
df.drop(columns= "City")
df

      Name  Age  Marks       City  Passed
0    Alice   20     90    Chitwan    True
1      Bob   22     83    Pokhara   False
2  Charlie   21     97   Lalitpur    True
3    David   23     93  Bhaktapur    True
4      Eva   19    100  Kathmandu    True

Sorting and Filtering Data

In [384]:
df.sort_values(by = "Marks")

      Name  Age  Marks       City  Passed
1      Bob   22     83    Pokhara   False
0    Alice   20     90    Chitwan    True
3    David   23     93  Bhaktapur    True
2  Charlie   21     97   Lalitpur    True
4      Eva   19    100  Kathmandu    True

In [385]:
df.sort_values(by = "Marks", ascending= False)

      Name  Age  Marks       City  Passed
4      Eva   19    100  Kathmandu    True
2  Charlie   21     97   Lalitpur    True
3    David   23     93  Bhaktapur    True
0    Alice   20     90    Chitwan    True
1      Bob   22     83    Pokhara   False

In [386]:
df[df["Age"] > 20 ]

      Name  Age  Marks       City  Passed
1      Bob   22     83    Pokhara   False
2  Charlie   21     97   Lalitpur    True
3    David   23     93  Bhaktapur    True

In [387]:
df[(df["Marks"] > 80) & (df["Marks"] < 90)]

  Name  Age  Marks     City  Passed
1  Bob   22     83  Pokhara   False

In [388]:
df[df["City"] == "Kathmandu"]

  Name  Age  Marks       City  Passed
4  Eva   19    100  Kathmandu    True

Handling Missing Values

In [389]:
data = {
    "Name": ["Ram", "Sita", "Hari", "Gita", "John"],
    "Age": [20, 21, None, 22, 20],
    "Marks": [80, None, 75, 90, 85]
}

df = pd.DataFrame(data)

In [390]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     4 non-null      float64
 2   Marks   4 non-null      float64
dtypes: float64(2), str(1)
memory usage: 252.0 bytes

In [391]:
fill_val = df["Age"].mean()
df["Age"] = df["Age"].fillna(fill_val)
df

   Name    Age  Marks
0   Ram  20.00   80.0
1  Sita  21.00    NaN
2  Hari  20.75   75.0
3  Gita  22.00   90.0
4  John  20.00   85.0

In [392]:
df["Marks"] = df["Marks"].fillna(0)
df

   Name    Age  Marks
0   Ram  20.00   80.0
1  Sita  21.00    0.0
2  Hari  20.75   75.0
3  Gita  22.00   90.0
4  John  20.00   85.0

In [393]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      float64
 2   Marks   5 non-null      float64
dtypes: float64(2), str(1)
memory usage: 252.0 bytes

Grouping and Aggregation

In [394]:
data = {
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance"],
    "Employee": ["A", "B", "C", "D", "E", "F"],
    "Salary": [50000, 40000, 60000, 55000, 45000, 65000]
}

df = pd.DataFrame(data)

In [395]:
df["Salary"].mean()

np.float64(52500.0)

In [396]:
df["Salary"].max()

np.int64(65000)

In [397]:
df["Salary"].min()

np.int64(40000)

In [400]:
avg_sal = df.groupby("Department")["Salary"].mean()
print(avg_sal)

Department
Finance    60000.0
HR         42500.0
IT         55000.0
Name: Salary, dtype: float64

In [401]:
max_sal =df.groupby("Department")["Salary"].max()
print(max_sal)

Department
Finance    65000
HR         45000
IT         60000
Name: Salary, dtype: int64