Data integration using join, concat

In [2]:
import pandas as pd

In [ ]:
df1 = pd.DataFrame({
    "Account No": [1001, 1002, 1003, 1004, 1005],
    "Name": ["Aarav Sharma", "Priya Singh", "Rohan Thapa", "Anisha Gurung",
             "Suman Karki"],
    "Age": [24, 31, 27, 22, 35]
})

df2 = pd.DataFrame({
    "Account No": [2001, 2002, 2003, 2004, 2005],
    "Name": ["Bikash Rai", "Sneha Joshi", "Nabin Shrestha", "Riya Adhikari",
             "Kiran Magar"],
    "Age": [29, 26, 33, 21, 38]
})

# "Concatenation"

In [ ]:
pd.concat([df1,df2],axis = 0,ignore_index= True)

   Account No            Name  Age
0        1001    Aarav Sharma   24
1        1002     Priya Singh   31
2        1003     Rohan Thapa   27
3        1004   Anisha Gurung   22
4        1005     Suman Karki   35
5        2001      Bikash Rai   29
6        2002     Sneha Joshi   26
7        2003  Nabin Shrestha   33
8        2004   Riya Adhikari   21
9        2005     Kiran Magar   38

In [ ]:
df1 = pd.DataFrame({
    "Account No": [1001, 1002, 1003, 1004, 1005],
    "Name": ["Aarav Sharma", "Priya Singh", "Rohan Thapa", "Anisha Gurung", 
             "Suman Karki"],
    "Age": [24, 31, 27, 22, 35]
})

df2 = pd.DataFrame({
    "Account No": [1001, 1002, 1003, 1004, 1005],
    "principle": [500,600,700,800,900],
    "interest": [2.9, 2.6, 3.3, 2.1, 3.8]
})

In [ ]:
pd.concat([df1,df2],axis = 1)

   Account No           Name  Age  Account No  principle  interest
0        1001   Aarav Sharma   24        1001        500       2.9
1        1002    Priya Singh   31        1002        600       2.6
2        1003    Rohan Thapa   27        1003        700       3.3
3        1004  Anisha Gurung   22        1004        800       2.1
4        1005    Suman Karki   35        1005        900       3.8

## Merging

In [ ]:
df1 = pd.DataFrame({
    "Account No": [1001, 1002, 1003, 1004, 1005],
    "Name": ["Aarav Sharma", "Priya Singh", "Rohan Thapa", "Anisha Gurung",
             "Suman Karki"],
    "Age": [24, 31, 27, 22, 35]
})

df2 = pd.DataFrame({
    "Account No": [1001, 1002, 1003, 1006, 1007],
    "principle": [500, 600, 700, 800, 900],
    "interest": [2.9, 2.6, 3.3, 2.1, 3.8]
})

In [28]:
pd.merge(df1,df2, how = "inner", on = "Account No")

   Account No          Name  Age  principle  interest
0        1001  Aarav Sharma   24        500       2.9
1        1002   Priya Singh   31        600       2.6
2        1003   Rohan Thapa   27        700       3.3

In [29]:
pd.merge(df1,df2, how = "outer", on = "Account No")

   Account No           Name   Age  principle  interest
0        1001   Aarav Sharma  24.0      500.0       2.9
1        1002    Priya Singh  31.0      600.0       2.6
2        1003    Rohan Thapa  27.0      700.0       3.3
3        1004  Anisha Gurung  22.0        NaN       NaN
4        1005    Suman Karki  35.0        NaN       NaN
5        1006            NaN   NaN      800.0       2.1
6        1007            NaN   NaN      900.0       3.8

In [30]:
pd.merge(df1,df2, how = "right", on = "Account No")

   Account No          Name   Age  principle  interest
0        1001  Aarav Sharma  24.0        500       2.9
1        1002   Priya Singh  31.0        600       2.6
2        1003   Rohan Thapa  27.0        700       3.3
3        1006           NaN   NaN        800       2.1
4        1007           NaN   NaN        900       3.8

# Join

In [32]:
df1.join(df2, how = "inner" ,lsuffix= "_left")

   Account No_left           Name  Age  Account No  principle  interest
0             1001   Aarav Sharma   24        1001        500       2.9
1             1002    Priya Singh   31        1002        600       2.6
2             1003    Rohan Thapa   27        1003        700       3.3
3             1004  Anisha Gurung   22        1006        800       2.1
4             1005    Suman Karki   35        1007        900       3.8